language: node_js
node_js:
  - "8"
cache:
  directories:
    - "node_modules"
  yarn: true
before_script:
  - "yarn"
script:
  - "yarn jest:unit"
  - "yarn jest:integration"
  - "yarn format"
  - "yarn lint"

