// flow-typed signature: 109f64d227786c49096a0616cb6e9e2d
// flow-typed version: <<STUB>>/creasync_v^0.1.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'creasync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'creasync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'creasync/lib/creasync' {
  declare module.exports: any;
}

declare module 'creasync/src/creasync' {
  declare module.exports: any;
}

// Filename aliases
declare module 'creasync/lib/creasync.js' {
  declare module.exports: $Exports<'creasync/lib/creasync'>;
}
declare module 'creasync/src/creasync.js' {
  declare module.exports: $Exports<'creasync/src/creasync'>;
}
