// flow-typed signature: 8f466382a60f80b9fab678134468e831
// flow-typed version: <<STUB>>/grunt-contrib-copy_v^1.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-contrib-copy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-contrib-copy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-contrib-copy/tasks/copy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-contrib-copy/tasks/copy.js' {
  declare module.exports: $Exports<'grunt-contrib-copy/tasks/copy'>;
}
