// flow-typed signature: e2aefed69c9fccac6f131e3d7d487211
// flow-typed version: <<STUB>>/react-async-component_v^1.0.0-beta.3/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-async-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-async-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-async-component/commonjs/asyncComponent' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/AsyncComponentProvider' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/createAsyncContext' {
  declare module.exports: any;
}

declare module 'react-async-component/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-async-component/umd/react-async-component' {
  declare module.exports: any;
}

declare module 'react-async-component/umd/react-async-component.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-async-component/commonjs/asyncComponent.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/asyncComponent'>;
}
declare module 'react-async-component/commonjs/AsyncComponentProvider.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/AsyncComponentProvider'>;
}
declare module 'react-async-component/commonjs/createAsyncContext.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/createAsyncContext'>;
}
declare module 'react-async-component/commonjs/index.js' {
  declare module.exports: $Exports<'react-async-component/commonjs/index'>;
}
declare module 'react-async-component/umd/react-async-component.js' {
  declare module.exports: $Exports<'react-async-component/umd/react-async-component'>;
}
declare module 'react-async-component/umd/react-async-component.min.js' {
  declare module.exports: $Exports<'react-async-component/umd/react-async-component.min'>;
}
